### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [kriskuiper/project-tech#2]
> "When I am searching for a date to cycle with, I want to know what others are doing and where they are cycling, so I can find a date that I can cycle with."

Solid Job story, very specific! Based on the way it's currently written there's a lot to enhance / how you can interpret it, you will need some components such as a map of some sort or track geolocation. Make sure you start with a mvp (text only?) and then enhance.

So indeed, start with a _status where the user can 'say' what there are currently working on or what they are doing._  and then explore further. _some kind of feed where all users can track the activities of possible dates nearby._

**Comment by kriskuiper** [comment]
Thanks voor de positieve feedback en je tips!
